[package]
name = "rfs-backend"
version = "0.1.0"
authors = ["zipper"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed="*"
actix-web = "*"
actix-rt = "*"
actix-web-actors = "*"
actix = "*"
mime_guess = "*"
